src/Entity/Diagnostico.php
<?php

namespace App\Entity;

use App\Repository\DiagnosticoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DiagnosticoRepository::class)
 */
class Diagnostico
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    
    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $tipo_diagnostico;

  
    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $solicitud;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $procedimiento;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $interconsulta;

    /**
     * @ORM\ManyToOne(targetEntity=Pacientes::class, inversedBy="diagnosticos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $pacientes;

    /**
     * @ORM\ManyToOne(targetEntity=CIE::class, inversedBy="diagnosticos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $cie;

    /**
     * @ORM\OneToMany(targetEntity=Tratamiento::class, mappedBy="diagnostico",orphanRemoval=true )
     */
    private $tratamiento;

    /**
     * @ORM\ManyToOne(targetEntity=Consulta::class, inversedBy="diagnosticos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $consulta;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $solicitud_complementaria;

    public function __construct()
    {
        $this->tratamiento = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDignostico(): ?string
    {
        return $this->dignostico;
    }

    public function setDignostico(?string $dignostico): self
    {
        $this->dignostico = strtoupper ($dignostico);

        return $this;
    }

    public function getTipoDiagnostico(): ?string
    {
        return $this->tipo_diagnostico;
    }

    public function setTipoDiagnostico(?string $tipo_diagnostico): self
    {
        $this->tipo_diagnostico = strtoupper ($tipo_diagnostico);

        return $this;
    }


    public function getSolicitud(): ?string
    {
        return $this->solicitud;
    }

    public function setSolicitud(?string $solicitud): self
    {
        $this->solicitud = strtoupper($solicitud);

        return $this;
    }

    public function getProcedimiento(): ?string
    {
        return $this->procedimiento;
    }

    public function setProcedimiento(?string $procedimiento): self
    {
        $this->procedimiento = strtoupper($procedimiento);

        return $this;
    }

    public function getInterconsulta(): ?string
    {
        return $this->interconsulta;
    }

    public function setInterconsulta(?string $interconsulta): self
    {
        $this->interconsulta = strtoupper($interconsulta);

        return $this;
    }

    public function getPacientes(): ?Pacientes
    {
        return $this->pacientes;
    }

    public function setPacientes(?Pacientes $pacientes): self
    {
        $this->pacientes = $pacientes;

        return $this;
    }

    public function getCie(): ?CIE
    {
        return $this->cie;
    }

    public function setCie(?CIE $cie): self
    {
        $this->cie = $cie;

        return $this;
    }



    public function getConsulta(): ?Consulta
    {
        return $this->consulta;
    }

    public function setConsulta(?Consulta $consulta): self
    {
        $this->consulta = $consulta;

        return $this;
    }

    public function getSolicitudComplementaria(): ?string
    {
        return $this->solicitud_complementaria;
    }

    public function setSolicitudComplementaria(?string $solicitud_complementaria): self
    {
        $this->solicitud_complementaria = strtoupper($solicitud_complementaria);

        return $this;
    }

    /**
     * @return Collection|Tratamiento[]
     */
    public function getTratamiento(): Collection
    {
        return $this->tratamiento;
    }

    public function addTratamiento(Tratamiento $tratamiento): self
    {
        if (!$this->tratamiento->contains($tratamiento)) {
            $this->tratamiento[] = $tratamiento;
            $tratamiento->setDiagnostico($this);
        }

        return $this;
    }

    public function removeTratamiento(Tratamiento $tratamiento): self
    {
        if ($this->tratamiento->removeElement($tratamiento)) {
            // set the owning side to null (unless already changed)
            if ($tratamiento->getDiagnostico() === $this) {
                $tratamiento->setDiagnostico(null);
            }
        }

        return $this;
    }
}

src/Form/DiagnosticoType.php
<?php

namespace App\Form;

use App\Entity\CIE;
use App\Entity\Diagnostico;
use App\Entity\Medicamentos;
use App\Entity\Pacientes;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DiagnosticoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('cie',EntityType::class,[
            'label'=>'Clasificación Internacional de Enfermedades CIE',
            'placeholder'=>'Seleccione una Enfermedad',
            'class'=>CIE::class,
            'choice_label'=>function (CIE $materia) {
                return  $materia->getCodigo(). ': ' . $materia->getDescripcion();},
            'attr' => ['data-select' => 'true']
        ])
            
            ->add('tipo_diagnostico',ChoiceType::class,[
                'label'=>'Tipo de Diagnóstico',
                'choices'=>[
                    'Escoja el tipo de diagnóstico' => 'Escoja el tipo de diagnóstico',
                    'PRESUNTIVO' => 'PRESUNTIVO',
                    'DEFINITIVO' => 'DEFINITIVO',
                   ]
            ])
            ->add('solicitud',TextType::class,[
                'required'=>false,
                'label'=>'Pedido de Examen de Laboratorio',
               'attr' => ['class' => 'text-uppercase' ], 
                
            ])

            ->add('solicitud_complementaria',TextType::class,[
                'required'=>false,
                'label'=>'Pedido de Examen Complementario',
               
               'attr' => ['class' => 'text-uppercase' ], 
                
            ])

            ->add('procedimiento',TextType::class,[
                'required'=>false,
                'label'=>'Pedido de Fisioterapia',

                'attr' => ['class' => 'text-uppercase' ], 
            ])

            ->add('interconsulta',TextType::class,[
                'required'=>false,
                'label'=>'Pedido de Interconsulta',
                'attr' => ['class' => 'text-uppercase' ], 
            ])


            ->getForm();
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            //'data_class' => Diagnostico::class,
        ]);
    }
}

src/Controller/DiagnosticoController.php
<?php

namespace App\Controller;

use App\Entity\Consulta;
use App\Entity\Diagnostico;
use App\Entity\Pacientes;
use App\Entity\Tratamiento;
use App\Form\DiagnosticoEdit;
use App\Form\DiagnosticoEdit2;
use App\Form\DiagnosticoType;
use App\Repository\ConsultaRepository;
use App\Repository\DiagnosticoRepository;
use App\Repository\PacientesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/diagnostico")
 * @IsGranted("IS_AUTHENTICATED_FULLY",message="No tiene acceso a esta pagina")
 */
class DiagnosticoController extends AbstractController
{
    /**
     * @Route("/", name="diagnostico_index", methods={"GET"})
     */
    public function index(DiagnosticoRepository $diagnosticoRepository): Response
    {
        return $this->render('diagnostico/index.html.twig', [
            'diagnosticos' => $diagnosticoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/paciente/{id}/consulta/{c}", name="diagnostico_new", methods={"GET","POST"})
     */
    public function new(Request $request,$id,$c,PacientesRepository $pacientesRepository, ConsultaRepository $consultaRepository): Response
    {
        $em= $this->getDoctrine()->getManager();
        $paciente= $em->getRepository(Pacientes::class)->find($id);
        $consulta= $em->getRepository(Consulta::class)->find($c);
        $fecha_consulta = $consulta->getFechaAtencion();
        $a=$pacientesRepository->paciennte_Diagnostico($paciente->getId(),$consulta->getId());
        $a2=$pacientesRepository->paciennte_Diagnostico_full($paciente->getId(),$consulta->getId(),$fecha_consulta);
        $tr=$pacientesRepository->paciennte_Diagnostico2($paciente->getId(),$consulta->getId());
        $form = $this->createForm(DiagnosticoType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data= $form->getData();
            $diagnostico = new Diagnostico();
            $diagnostico->setPacientes($paciente);
            $diagnostico->setConsulta($consulta);
            $diagnostico->setCie($data['cie']);
            $diagnostico->setTipoDiagnostico($data['tipo_diagnostico']);
            $diagnostico->setSolicitud($data['solicitud']);
            $diagnostico->setProcedimiento($data['procedimiento']);
            $diagnostico->setInterconsulta($data['interconsulta']);
            $diagnostico->setSolicitudComplementaria($data['solicitud_complementaria']);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($diagnostico);
            $entityManager->flush();
           $this->addFlash('exito','Registro Guardado con Éxito');

           return $this->redirect($request->getUri());
           
        }

        return $this->render('diagnostico/new.html.twig', [
             'pedidos'=> $tr,
            'antecedentes'=>$a,
            'antecedentes2'=>$a2,
            'consulta'=>$consulta,
            'paciente'=>$paciente,
            'c'=>$consultaRepository->consulta_examene($consulta->getId()),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="diagnostico_show", methods={"GET"})
     */
    public function show(Diagnostico $diagnostico): Response
    {
        return $this->render('diagnostico/show.html.twig', [
            'diagnostico' => $diagnostico,
        ]);
    }

    /**
     * @Route("/paciente/{p}/antecedente/{id}/consulta/{c}", name="diagnostico_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Diagnostico $diagnostico,$p,$c): Response
    {
        $em= $this->getDoctrine()->getManager();
        $paciente= $em->getRepository(Pacientes::class)->find($p);
        $consulta= $em->getRepository(Consulta::class)->find($c);
        $form = $this->createForm(DiagnosticoEdit::class, $diagnostico);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('exito','Registro Actualizado con éxito');
            return $this->redirect($request->getUri());
        }

        return $this->render('diagnostico/edit.html.twig', [
            'consulta'=>$consulta,
            'paciente'=>$paciente,
            'diagnostico' => $diagnostico,
            'form' => $form->createView(),
        ]);
    }

    
       /**
     * @Route("/copiar/paciente/{p}/antecedente/{id}/consulta/{c}", name="diagnostico_copiar", methods={"GET","POST"})
     */
    public function copiar(Request $request, Diagnostico $diagnostico,$p,$c): Response
    {
        $em= $this->getDoctrine()->getManager();
        $paciente= $em->getRepository(Pacientes::class)->find($p);
        $consulta= $em->getRepository(Consulta::class)->find($c);
        $form = $this->createForm(DiagnosticoEdit2::class, $diagnostico);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data= $form->getData();
            $diagnostico2 = new Diagnostico();
            $diagnostico2->setPacientes($paciente);
            $diagnostico2->setConsulta($consulta);
            $diagnostico2->setCie($data->getCie());
            $diagnostico2->setTipoDiagnostico($data->getTipoDiagnostico());
            $diagnostico2->setSolicitud($data->getSolicitud());
            $diagnostico2->setProcedimiento($data->getProcedimiento());
            $diagnostico2->setInterconsulta($data->getInterconsulta());
            $diagnostico2->setSolicitudComplementaria($data->getSolicitudComplementaria());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($diagnostico2);
            $entityManager->flush();
            $this->addFlash('exito','Registro copiado con exito en la consulta actual');
            return $this->redirect($request->getUri());
        }

        return $this->render('diagnostico/copiar.html.twig', [
            'consulta'=>$consulta,
            'paciente'=>$paciente,
            'diagnostico' => $diagnostico,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{id}", name="delate_diagnostico")
     * @Method({"DELETE"})
     */
    public function delete($id) 
    {
        $antecedente= $this->getDoctrine()->getRepository(Diagnostico::class)->find($id);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($antecedente);
        $entityManager->flush();
        $response = new Response();
        $response->send();
    }
}

templates/diagnostico/_delete_form.html.twig
<form method="post" action="{{ path('diagnostico_delete', {'id': diagnostico.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ diagnostico.id) }}">
    <button class="btn btn-block btn-outline-danger btn-sm">
<i class="fas fa-trash-alt"> 
Eliminar
</i>
</button>
</form>

templates/diagnostico/_form.html.twig
{{ form_start(form) }}

    {{ form_widget(form) }}

    <button class="btn btn-block bg-gradient-primary btn-sm">
    <i class="fas fa-save">{{ button_label|default('Guardar') }}</i>
    </button>
{{ form_end(form) }}

templates/diagnostico/_form2.html.twig
{{ form_start(form) }}

    {{ form_widget(form) }}

    <button class="btn btn-block bg-gradient-primary btn-sm">
    <i class="fas fa-save">{{ button_label|default('Guardar') }}</i>
    </button>
{{ form_end(form) }}

templates/diagnostico/copiar.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Diagnostico{% endblock %}

{% block body %}
<div class="card-body p-5 bg-white rounded">
    <h6>Diagnóstico para el/la Paciente: <b> {{diagnostico.pacientes.pnombre}} {{diagnostico.pacientes.snombre}} {{diagnostico.pacientes.papellido}} {{diagnostico.pacientes.sapellido}}</b></h6>
    <h6>Motivo de la Consulta: <b>{{ diagnostico.consulta.motivoconsulta }}</b>  Fecha: <b>{{ diagnostico.consulta.fechaatencion  ? diagnostico.consulta.fechaatencion|date('Y-m-d') : '' }}</b> Médico: <b>{{consulta.employed.Nombre }} {{consulta.employed.Apellido }}</b></h6>
</br>
{% for flash_message in app.session.flashbag.get('exito') %}
<div class="alert alert-success" role="alert">
       {{ flash_message }}
</div>
{% endfor %}
    {{ include('diagnostico/_form2.html.twig', {'button_label': 'Copiar'}) }}
    
    <a href="{{ path('diagnostico_new', {id: paciente.id, c: consulta.id}) }}">
    
    <button class="btn btn-block btn-outline-warning btn-sm">
<i class="fas fa-chevron-left">Regresar a ficha médica</i>
</button>
      </a>

</div>
{% endblock %}


{% block javascripts %}

    <script type="text/javascript">
        $(document).ready(function() {
          $('select[data-select="true"]').select2({
                minimumInputLength: 2,
             allowClear: true,
             placeholder: 'Seleccione un medicamento->'
          });
        });
    </script>
  

 


  

   {% endblock %}

templates/diagnostico/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Diagnostico{% endblock %}

{% block body %}
<div class="card-body p-5 bg-white rounded">
    <h6>Editar Diagnóstico para el/la Paciente: <b> {{paciente.pnombre}} {{paciente.snombre}} {{paciente.papellido}} {{paciente.sapellido}}</b></h6>
    <h6>Motivo de la Consulta: <b>{{ consulta.motivoconsulta }}</b>  Fecha: <b>{{ consulta.fechaatencion  ? consulta.fechaatencion|date('Y-m-d') : '' }}</b> Médico: <b>{{consulta.employed.Nombre }} {{consulta.employed.Apellido }}</b></h6>
</br>
    {{ include('diagnostico/_form.html.twig', {'button_label': ' Actualizar'}) }}
    
    <a href="{{ path('diagnostico_new', {id: paciente.id, c: consulta.id}) }}">
    
    <button class="btn btn-block btn-outline-warning btn-sm">
<i class="fas fa-chevron-left">Regresar a ficha médica</i>
</button>
      </a>

</div>
{% endblock %}


{% block javascripts %}

    <script type="text/javascript">
        $(document).ready(function() {
          $('select[data-select="true"]').select2({
                minimumInputLength: 2,
             allowClear: true,
             placeholder: 'Seleccione un medicamento->'
          });
        });
    </script>
  

 


  

   {% endblock %}

templates/diagnostico/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Diagnóstico{% endblock %}

{% block body %}
    <h1>Diagnóstico</h1>
    <div class="table-responsive">
    <table id="exmaple" style="width:100%" class="content-table table-sm">
        <thead>
            <tr>
                <th>Id</th>
                <th>Tipo Diagnóstico</th>
                <th>Aptitud</th>
                <th>Exámenes Laboratorio</th>
                <th>Fisioterapia</th>
                <th>Recomendaciones</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for diagnostico in diagnosticos %}
            <tr>
                <td>{{ diagnostico.id }}</td>
                <td>{{ diagnostico.tipoDiagnostico }}</td>
                <td>{{ diagnostico.aptitud }}</td>
                <td>{{ diagnostico.observacion }}</td>
                <td>{{ diagnostico.limitacion }}</td>
                <td>{{ diagnostico.recomendciones }}</td>
                <td>
                    <a href="{{ path('diagnostico_show', {'id': diagnostico.id}) }}">Mostrar</a>
                    <a href="{{ path('diagnostico_edit', {'id': diagnostico.id}) }}">Editar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">No Existen Registros</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

templates/diagnostico/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Diagnostico{% endblock %}

{% block body %}
    <h1>Diagnostico</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ diagnostico.id }}</td>
            </tr>
            <tr>
                <th>Tipo Diagnóstico</th>
                <td>{{ diagnostico.tipoDiagnostico }}</td>
            </tr>
            <tr>
                <th>Aptitud</th>
                <td>{{ diagnostico.aptitud }}</td>
            </tr>
            <tr>
                <th>Observación</th>
                <td>{{ diagnostico.observacion }}</td>
            </tr>
            <tr>
                <th>Limitación</th>
                <td>{{ diagnostico.limitacion }}</td>
            </tr>
            <tr>
                <th>Recomendaciones</th>
                <td>{{ diagnostico.recomendciones }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('diagnostico_index') }}">back to list</a>

    <a href="{{ path('diagnostico_edit', {'id': diagnostico.id}) }}">edit</a>

    {{ include('diagnostico/_delete_form.html.twig') }}
{% endblock %}