src/Entity/AntPatologicos.php
<?php

namespace App\Entity;

use App\Repository\AntPatologicosRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AntPatologicosRepository::class)
 */
class AntPatologicos
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $piel_anexos;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $organos_sentidos;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $respiratorio;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cardiovascular;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $digestivo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $genito_urinario;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $musculo_esqueletico;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $endocrino;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $hemolinfatico;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nervioso;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $enfermedad_actual;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $observaciones;

    /**
     * @ORM\ManyToOne(targetEntity=Pacientes::class, inversedBy="antPatologicos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $pacientes;

    /**
     * @ORM\ManyToOne(targetEntity=Consulta::class, inversedBy="antPatologicos")
     * @ORM\JoinColumn(nullable=true)
     */
    private $consulta;

       /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $creatdate;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedate;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPielAnexos(): ?string
    {
        return $this->piel_anexos;
    }

    public function setPielAnexos(?string $piel_anexos): self
    {
        $this->piel_anexos = strtoupper($piel_anexos);

        return $this;
    }

    public function getOrganosSentidos(): ?string
    {
        return $this->organos_sentidos;
    }

    public function setOrganosSentidos(?string $organos_sentidos): self
    {
        $this->organos_sentidos = strtoupper($organos_sentidos);

        return $this;
    }

    public function getRespiratorio(): ?string
    {
        return $this->respiratorio;
    }

    public function setRespiratorio(?string $respiratorio): self
    {
        $this->respiratorio = strtoupper($respiratorio);

        return $this;
    }

    public function getCardiovascular(): ?string
    {
        return $this->cardiovascular;
    }

    public function setCardiovascular(?string $cardiovascular): self
    {
        $this->cardiovascular = strtoupper($cardiovascular);

        return $this;
    }

    public function getDigestivo(): ?string
    {
        return $this->digestivo;
    }

    public function setDigestivo(?string $digestivo): self
    {
        $this->digestivo = strtoupper($digestivo);

        return $this;
    }

    public function getGenitoUrinario(): ?string
    {
        return $this->genito_urinario;
    }

    public function setGenitoUrinario(?string $genito_urinario): self
    {
        $this->genito_urinario = strtoupper($genito_urinario);

        return $this;
    }

    public function getMusculoEsqueletico(): ?string
    {
        return $this->musculo_esqueletico;
    }

    public function setMusculoEsqueletico(?string $musculo_esqueletico): self
    {
        $this->musculo_esqueletico = strtoupper($musculo_esqueletico);

        return $this;
    }

    public function getEndocrino(): ?string
    {
        return $this->endocrino;
    }

    public function setEndocrino(?string $endocrino): self
    {
        $this->endocrino = strtoupper($endocrino);

        return $this;
    }

    public function getHemolinfatico(): ?string
    {
        return $this->hemolinfatico;
    }

    public function setHemolinfatico(?string $hemolinfatico): self
    {
        $this->hemolinfatico = strtoupper($hemolinfatico);

        return $this;
    }

    public function getNervioso(): ?string
    {
        return $this->nervioso;
    }

    public function setNervioso(?string $nervioso): self
    {
        $this->nervioso = strtoupper($nervioso);

        return $this;
    }

    
  

    public function getEnfermedadActual(): ?string
    {
        return $this->enfermedad_actual;
    }

    public function setEnfermedadActual(?string $enfermedad_actual): self
    {
        $this->enfermedad_actual = strtoupper($enfermedad_actual);

        return $this;
    }

    public function getObservaciones(): ?string
    {
        return $this->observaciones;
    }

    public function setObservaciones(?string $observaciones): self
    {
        $this->observaciones = strtoupper($observaciones);

        return $this;
    }

    public function getPacientes(): ?Pacientes
    {
        return $this->pacientes;
    }

    public function setPacientes(?Pacientes $pacientes): self
    {
        $this->pacientes =  $pacientes;

        return $this;
    }

    public function getConsulta(): ?Consulta
    {
        return $this->consulta;
    }

    public function setConsulta(?Consulta $consulta): self
    {
        $this->consulta = $consulta;

        return $this;
    }

    public function getCreatdate(): ?\DateTimeInterface
    {
        return $this->creatdate;
    }

    public function setCreatdate(?\DateTimeInterface $creatdate): self
    {
        $this->creatdate = $creatdate;

        return $this;
    }

    public function getUpdatedate(): ?\DateTimeInterface
    {
        return $this->updatedate;
    }

    public function setUpdatedate(?\DateTimeInterface $updatedate): self
    {
        $this->updatedate = $updatedate;

        return $this;
    }
}

src/Form/AntPatologicosType.php
<?php

namespace App\Form;

use App\Entity\AntPatologicos;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AntPatologicosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            
            ->add('enfermedad_actual',TextType::class,[
                'required' => false,
                'label'=>'Enfermedad Actual', 
                'attr' => ['class' => 'text-uppercase' ],
            ])
            ->add('piel_anexos',TextType::class,[
                'required' => false,
                'label'=>'Piel-Anexos ', 
                'attr' => ['class' => 'text-uppercase' ],
            ])
            ->add('organos_sentidos',TextType::class,[
                'required' => false,
                'label'=>'Órganos de los sentidos', 
                'attr' => ['class' => 'text-uppercase' ],
            ])
            ->add('respiratorio',TextType::class,[
                'required' => false,
                'label'=>'Respiratorio', 
                'attr' => ['class' => 'text-uppercase' ],
            ])
            ->add('cardiovascular',TextType::class,[
                'required' => false,
                'label'=>'Cardio-vascular', 
                'attr' => ['class' => 'text-uppercase' ],
            ])
            ->add('digestivo',TextType::class,[
                'required' => false,
                'label'=>'Digestivo', 
                'attr' => ['class' => 'text-uppercase' ],
            ])
            ->add('genito_urinario',TextType::class,[
                'required' => false,
                'label'=>'Génito-Urinario', 
                'attr' => ['class' => 'text-uppercase' ],
            ])
            ->add('musculo_esqueletico',TextType::class,[
                'required' => false,
                'label'=>'Músculo Esquelético', 
                'attr' => ['class' => 'text-uppercase' ],
            ])
            ->add('endocrino',TextType::class,[
                'required' => false,
                'label'=>'Endócrino', 
                'attr' => ['class' => 'text-uppercase' ],
            ])
            ->add('hemolinfatico',TextType::class,[
                'required' => false,
                'label'=>'Hemo linfático', 
                'attr' => ['class' => 'text-uppercase' ],
            ])
            ->add('nervioso',TextType::class,[
                'required' => false,
                'label'=>'Nervioso', 
                'attr' => ['class' => 'text-uppercase' ],
            ])
            ->add('observaciones',TextType::class,[
                'required' => false,
                'label'=>'Observaciones', 
                'attr' => ['class' => 'text-uppercase' ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AntPatologicos::class,
        ]);
    }
}

src/Controller/AntPatologicosController.php
<?php

namespace App\Controller;

use App\Entity\AntPatologicos;
use App\Entity\Consulta;
use App\Entity\Pacientes;
use App\Form\AntPatologicosType;
use App\Repository\AntPatologicosRepository;
use App\Repository\ConsultaRepository;
use App\Repository\PacientesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use DateTime;
/**
 * @Route("/ant/patologicos")
 * @IsGranted("IS_AUTHENTICATED_FULLY",message="No tiene acceso a esta pagina")
 */
class AntPatologicosController extends AbstractController
{
    /**
     * @Route("/", name="ant_patologicos_index", methods={"GET"})
     */
    public function index(AntPatologicosRepository $antPatologicosRepository): Response
    {
        return $this->render('ant_patologicos/index.html.twig', [
            'ant_patologicos' => $antPatologicosRepository->findAll(),
        ]);
    }

    /**
     * @Route("/paciente{id}/consulta/{c}", name="ant_patologicos_new", methods={"GET","POST"})
     */
    public function new(Request $request,$id,$c,PacientesRepository $pacientesRepository, ConsultaRepository $consultaRepository,AntPatologicosRepository $antPatologicosRepository): Response
    {
        $em= $this->getDoctrine()->getManager();
        $paciente= $em->getRepository(Pacientes::class)->find($id);
        $consulta= $em->getRepository(Consulta::class)->find($c);
        $a2=$antPatologicosRepository->findBy(['pacientes'=>$paciente]);
        $antPatologico = new AntPatologicos();
        $form = $this->createForm(AntPatologicosType::class, $antPatologico);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $antPatologico->setPacientes($paciente);
            $antPatologico->setCreatdate(new DateTime());
            $entityManager->persist($antPatologico);
            $entityManager->flush();
            $this->addFlash('exito','Registro Guardado con Éxito');

            return $this->redirect($request->getUri());
        }

        return $this->render('ant_patologicos/new.html.twig', [
            'consulta'=>$consulta,
            'antecedentes2'=>$a2,
            'paciente'=>$paciente,
            'ant_patologico' => $antPatologico,
            'c'=>$consultaRepository->consulta_examene($consulta->getId()),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ant_patologicos_show", methods={"GET"})
     */
    public function show(AntPatologicos $antPatologico): Response
    {
        return $this->render('ant_patologicos/show.html.twig', [
            'ant_patologico' => $antPatologico,
        ]);
    }

    /**
     * @Route("/paciente/{p}/antecedente/{id}/consulta/{c}", name="ant_patologicos_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, AntPatologicos $antPatologico,$p,$c): Response
    {
        $em= $this->getDoctrine()->getManager();
        $paciente= $em->getRepository(Pacientes::class)->find($p);
        $consulta= $em->getRepository(Consulta::class)->find($c);
        $form = $this->createForm(AntPatologicosType::class, $antPatologico);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $antPatologico->setUpdatedate(new DateTime());
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('exito','Registro Actualizado con éxito');
            return $this->redirect($request->getUri());
        }

        return $this->render('ant_patologicos/edit.html.twig', [
            'consulta'=>$consulta,
            'paciente'=>$paciente,
            'ant_patologico' => $antPatologico,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="delate_patologicos")
     * @Method({"DELETE"})
     */
    public function delete($id)
    {
        $antecedente= $this->getDoctrine()->getRepository(AntPatologicos::class)->find($id);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($antecedente);
        $entityManager->flush();
        $response = new Response();
        $response->send();
       
    }
}

templates/ant_patologicos/_delete_form.html.twig
<form method="post" action="{{ path('ant_patologicos_delete', {'id': ant_patologico.id}) }}" onsubmit="return confirm('Está seguro de eliminar el item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ant_patologico.id) }}">
    <button class="btn btn-block btn-outline-danger btn-sm">
        <i class="fas fa-trash-alt"> 
            Eliminar
        </i>
    </button>
</form>

templates/ant_patologicos/_form.html.twig
{{ form_start(form) }}
<div class="row">
     <div class="col-md-12">
     </br>
                         {{ form_row(form.enfermedad_actual,{
                              attr: {
                                   'placeholder': 'Que Enfermedad Padece Actualmente ',
                               }
                                 }) }}
    </div>
</div>
 <div class="row">
     <div class="col-md-6">
                </br>
                         {{ form_row(form.piel_anexos,{
                              attr: {
                                   'placeholder': 'Piel Anexos',
                               }
                                 }) }}
     </div>
    

    <div class="col-md-6">
    </br>
                         {{ form_row(form.organos_sentidos,{
                              attr: {
                                   'placeholder': 'Órganos Sentidos',
                               }
                                 }) }}
    </div>

     <div class="col-md-6">
     </br>
                         {{ form_row(form.respiratorio,{
                              attr: {
                                   'placeholder': 'Respiratorio',
                               }
                                 }) }}
    </div>
     <div class="col-md-6">
     </br>
                         {{ form_row(form.cardiovascular,{
                              attr: {
                                   'placeholder': 'Cardiovascular',
                               }
                                 }) }}
    </div>
     <div class="col-md-6">
     </br>
                         {{ form_row(form.digestivo,{
                              attr: {
                                   'placeholder': 'Digestivo',
                               }
                                 }) }}
    </div>
     <div class="col-md-6">
     </br>
                         {{ form_row(form.genito_urinario,{
                              attr: {
                                   'placeholder': 'Génito Urinario',
                               }
                                 }) }}
    </div>

     <div class="col-md-6">
     </br>
                         {{ form_row(form.musculo_esqueletico,{
                              attr: {
                                   'placeholder': 'Músculo Esquelético',
                               }
                                 }) }}
    </div>
     <div class="col-md-6">
     </br>
                         {{ form_row(form.endocrino,{
                              attr: {
                                   'placeholder': 'Endócrino',
                               }
                                 }) }}
    </div>
     <div class="col-md-6">
     </br>
                         {{ form_row(form.hemolinfatico,{
                              attr: {
                                   'placeholder': 'Hemolinfático',
                               }
                                 }) }}
    </div>
     <div class="col-md-6">
     </br>
                         {{ form_row(form.nervioso,{
                              attr: {
                                   'placeholder': 'Nervioso',
                               }
                                 }) }}
    </div>
     
     <div class="col-md-12">
     </br>
                         {{ form_row(form.observaciones,{
                              attr: {
                                   'placeholder': 'Observaciones',
                               }
                                 }) }}
                                 </br>
    </div>
   
</div>
     <button class="btn btn-block bg-gradient-primary btn-sm">
              <i class="fas fa-save"> </i>  
              {{ button_label|default('Guardar') }}
              </button>
{{ form_end(form) }}
    </br>
    

templates/ant_patologicos/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Antecedente Patológicos{% endblock %}

{% block body %}
 <div class="card-body p-5 bg-white rounded">
    <h6>Editar Revisión de Órganos y Sistemas de: <b> {{paciente.pnombre}} {{paciente.snombre}} {{paciente.papellido}} {{paciente.sapellido}}</b></h6>
{% for flash_message in app.session.flashbag.get('exito') %}
    <div class="alert alert-success" role="alert">
       {{ flash_message }}
</div>
{% endfor %}
    {{ include('ant_patologicos/_form.html.twig', {'button_label': 'Actualizar'}) }}

     
    </div>
    <div>
    <a href="{{ path('ant_patologicos_new', {id: paciente.id, c:consulta.id}) }}">
     <button class="btn btn-block btn-outline-warning btn-sm">
<i class="fas fa-chevron-left">Regresar a la ficha médica</i>
</button>
      </a>
      </div>
{% endblock %}

      

templates/ant_patologicos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Revisión Actual de Órganos y Sistemas{% endblock %}

{% block body %}
    <h1>Revisión Actual de Órganos y Sistemas</h1>
    <div class="table-responsive">
    <table  id="exmaple" style="width:100%" class="content-table table-sm">
        <thead>
            <tr>
                <th>Enfermedad Actual</th>
                <th>Piel Anexos</th>
                <th>Órganos Sentidos</th>
                <th>Respiratorio</th>
                <th>Cardiovascular</th>
                <th>Digestivo</th>
                <th>Génito Urinario</th>
                <th>Músculo Esquelético</th>
                <th>Endocrino</th>
                <th>Hemolinfático</th>
                <th>Nervioso</th>
                <th>Observaciones</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for ant_patologico in ant_patologicos %}
            <tr>
                <td>{{ ant_patologico.enfermedadActual }}</td>
                <td>{{ ant_patologico.pielAnexos }}</td>
                <td>{{ ant_patologico.organosSentidos }}</td>
                <td>{{ ant_patologico.respiratorio }}</td>
                <td>{{ ant_patologico.cardiovascular }}</td>
                <td>{{ ant_patologico.digestivo }}</td>
                <td>{{ ant_patologico.genitoUrinario }}</td>
                <td>{{ ant_patologico.musculoEsqueletico }}</td>
                <td>{{ ant_patologico.endocrino }}</td>
                <td>{{ ant_patologico.hemolinfatico }}</td>
                <td>{{ ant_patologico.nervioso }}</td>
                <td>{{ ant_patologico.observaciones }}</td>
                <td>
                    <a class="dropdown-item" href="/ant/patologicos/paciente/{{consulta.PI}}/antecedente/{{consulta.id}}" style="font-size: 0.8em">Editar Antecedente</a>
                    <a href="#"  class="dropdown-item delete-article" data-id="{{consulta.id}}" style="font-size: 0.8em">Eliminar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="15">No existen registros</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
     
    </div>
    </div>
    <button class="btn btn-block bg-primary btn-sm">
    <a href="{{ path('ant_patologicos_new') }}">
    <i class="fas fa-plus-square">
                Crear Nuevo
            </i>
        </a>
    </button>
    
{% endblock %}

templates/ant_patologicos/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Antecedentes Patológicos{% endblock %}

{% block body %}

<div class="card-body p-5 bg-white rounded">

  {{ include('full_antecedentes/ant_base.html.twig') }}

    {{ include('ant_patologicos/_form.html.twig') }}
<br>
{% for flash_message in app.session.flashbag.get('exito') %}
    <div class="alert alert-success" role="alert">
       {{ flash_message }}
</div>
{% endfor %}
<div class="table-responsive">
    <table  id="example" style="width:100%" class="content-table table-lg">
        <thead>
            <tr>
                <th>Id</th>
                <th>Fecha de registro</th>
                <th>Fecha de edicion</th>
                <th>Enfermedad Actual </th>
                <th>Piel Anexos </th>
                <th>Órganos Sentidos </th>
                <th>Respiratorio </th>
                <th>Cardiovascular </th>
                <th>Digestivo </th>
                <th>Génito Urinario </th>
                <th>Músculo Esquelético </th>
                <th>Endócrino </th>
                <th>Hemolinfático </th>
                <th>Nervioso </th>
                <th>Observaciones </th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody id="articles">
        {% for ant_patologico in antecedentes2 %}
            <tr>
                <td>{{ant_patologico.id}}</td>
                <td>{{ ant_patologico.creatdate ? ant_patologico.creatdate|date('Y-m-d H:i:s') : ''  }}</td>
                <td>{{ ant_patologico.updatedate ? ant_patologico.updatedate|date('Y-m-d H:i:s') : ''  }}</td>
                <td>{{ ant_patologico.enfermedadactual }}</td>
                <td>{{ ant_patologico.pielanexos }}</td>
                <td>{{ ant_patologico.organossentidos }}</td>
                <td>{{ ant_patologico.respiratorio }}</td>
                <td>{{ ant_patologico.cardiovascular }}</td>
                <td>{{ ant_patologico.digestivo }}</td>
                <td>{{ ant_patologico.genitourinario}}</td>
                <td>{{ ant_patologico.musculoesqueletico }}</td>
                <td>{{ ant_patologico.endocrino }}</td>
                <td>{{ ant_patologico.hemolinfatico }}</td>
                <td>{{ ant_patologico.nervioso }}</td>
                <td>{{ ant_patologico.observaciones }}</td>
                <td> 
                <a  class="dropdown-item" href="{{ path('ant_patologicos_edit', {p: paciente.id, id: ant_patologico.id , c: consulta.id}) }}" style="font-size: 0.8em">Editar Antecedente</a>
                 <a href="#" class="dropdown-item delete-article" data-id="{{ant_patologico.id}}" style="font-size: 0.8em">Eliminar</a> 
                </td>
            </tr>
         {% if antecedentes2 is empty %}
           <tr>
              <td colspan="4">No hay registros disponibles</td>
           </tr>
         {% endif %}
           
        {% endfor %}
        </tbody>
    </table>
  </div>

</div>

{% endblock %}


{% block javascripts %}
  <script> 
       $(document).ready(function() {
        $('#example').DataTable( {

        
            language: {
            url: 'https://cdn.datatables.net/plug-ins/1.10.22/i18n/Spanish.json'
        },

       
         'responsive': true,
          order:[0, 'desc'],
         
  } );
    } );
 </script>



   <script type="text/javascript"> 
     window.onload= function(){
       document.getElementById("op1").style="background-color: #FDF4BC;";
     }
 </script>



<script>
  const articles = document.getElementById('articles');
   if (articles) {
     articles.addEventListener('click', e => {
       if (e.target.className === 'dropdown-item delete-article') {
         if (confirm('Esta seguro de eliminar este elemento?')) {
             const value = e.target.getAttribute('data-id');
              let route = "{{ path('delate_patologicos', { id: 'fileId_' }) }}";
              route = route.replace('fileId_', value);
   
           fetch(route, {
             method: 'DELETE'
           }).then(res => window.location.reload());
         }
       }
     });
   };
</script>
{% endblock %}

templates/ant_patologicos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}AntPatologicos{% endblock %}

{% block body %}
    <h1>AntPatologicos</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ant_patologico.id }}</td>
            </tr>
            <tr>
                <th>Piel_anexos</th>
                <td>{{ ant_patologico.pielAnexos }}</td>
            </tr>
            <tr>
                <th>Organos_sentidos</th>
                <td>{{ ant_patologico.organosSentidos }}</td>
            </tr>
            <tr>
                <th>Respiratorio</th>
                <td>{{ ant_patologico.respiratorio }}</td>
            </tr>
            <tr>
                <th>Cardiovascular</th>
                <td>{{ ant_patologico.cardiovascular }}</td>
            </tr>
            <tr>
                <th>Digestivo</th>
                <td>{{ ant_patologico.digestivo }}</td>
            </tr>
            <tr>
                <th>Genito_urinario</th>
                <td>{{ ant_patologico.genitoUrinario }}</td>
            </tr>
            <tr>
                <th>Musculo_esqueletico</th>
                <td>{{ ant_patologico.musculoEsqueletico }}</td>
            </tr>
            <tr>
                <th>Endocrino</th>
                <td>{{ ant_patologico.endocrino }}</td>
            </tr>
            <tr>
                <th>Hemolinfatico</th>
                <td>{{ ant_patologico.hemolinfatico }}</td>
            </tr>
            <tr>
                <th>Nervioso</th>
                <td>{{ ant_patologico.nervioso }}</td>
            </tr>
           
            <tr>
                <th>Enfermedad_actual</th>
                <td>{{ ant_patologico.enfermedadActual }}</td>
            </tr>
            <tr>
                <th>Observaciones</th>
                <td>{{ ant_patologico.observaciones }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('ant_patologicos_index') }}">back to list</a>

    <a href="{{ path('ant_patologicos_edit', {'id': ant_patologico.id}) }}">edit</a>

    {{ include('ant_patologicos/_delete_form.html.twig') }}
{% endblock %}