src/Entity/Employed.php
<?php

namespace App\Entity;

use App\Repository\EmployedRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EmployedRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"Cedula","email"},
 *     message="Este usuario ya existe"
 * )
 */
class Employed implements AdvancedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


     /**
     * @ORM\Column(type="string", length=10,unique=true)
     * @Assert\NotBlank()
     * @Assert\Length(
     *      min = 10,
     *      max = 10,
     * )
     */
    private $Cedula;


    /**
     * @ORM\Column(type="string", length=255,unique=true)
     * @Assert\Email(
     *     message = "El email '{{ value }}' no es valido."
     * )
     */
    private $email;

   

    /**
     * @ORM\Column(type="string", length=255, )
     */
    private $Nombre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Apellido;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $foto;




    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Assert\Range(
     *      max = "now"
     * )
     */
    private $Fecha_Ingreso;



    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Profesion;


    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $username;




    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    
    public function __construct()
    {
      
      
        $this->is_active = true;
        $this->Fecha_Ingreso= new \DateTime();
        $this->paralelo = new ArrayCollection();
        $this->consulta = new ArrayCollection();
        $this->reset_pasword = new ArrayCollection();
      
      
      
    }

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

     /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;


     /**
     * @ORM\Column(type="string", length=64)
     */
    private $estado;

    /**
     * @ORM\ManyToOne(targetEntity=Unidadesoperativas::class, inversedBy="employed")
     * @ORM\JoinColumn(nullable=false)
     */
    private $unidadesoperativas;

    /**
     * @ORM\OneToMany(targetEntity=Consulta::class, mappedBy="employed", orphanRemoval=true)
     */
    private $consulta;

   



 


    public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return true;
    }

    public function isCredentialsNonExpired()
    {
        return true;
    }

    public function isEnabled()
    {
        return $this->is_active;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
       

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getCedula(): ?string
    {
        return $this->Cedula;
    }

    public function setCedula(string $Cedula): self
    {
        $this->Cedula = $Cedula;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getApellido(): ?string
    {
        return $this->Apellido;
    }

    public function setApellido(string $Apellido): self
    {
        $this->Apellido = $Apellido;

        return $this;
    }

    public function getFoto(): ?string
    {
        return $this->foto;
    }

    public function setFoto(?string $foto): self
    {
        $this->foto = $foto;

        return $this;
    }


    public function getFechaIngreso(): ?\DateTimeInterface
    {
        return $this->Fecha_Ingreso;
    }

    public function setFechaIngreso(?\DateTimeInterface $Fecha_Ingreso): self
    {
        $this->Fecha_Ingreso = $Fecha_Ingreso;

        return $this;
    }

  
    public function getProfesion(): ?string
    {
        return $this->Profesion;
    }

    public function setProfesion(string $Profesion): self
    {
        $this->Profesion = $Profesion;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

    public function getUnidadesoperativas(): ?Unidadesoperativas
    {
        return $this->unidadesoperativas;
    }

    public function setUnidadesoperativas(?Unidadesoperativas $unidadesoperativas): self
    {
        $this->unidadesoperativas = $unidadesoperativas;

        return $this;
    }

    /**
     * @return Collection|Consulta[]
     */
    public function getConsulta(): Collection
    {
        return $this->consulta;
    }

    public function addConsultum(Consulta $consultum): self
    {
        if (!$this->consulta->contains($consultum)) {
            $this->consulta[] = $consultum;
            $consultum->setEmployed($this);
        }

        return $this;
    }

    public function removeConsultum(Consulta $consultum): self
    {
        if ($this->consulta->removeElement($consultum)) {
            // set the owning side to null (unless already changed)
            if ($consultum->getEmployed() === $this) {
                $consultum->setEmployed(null);
            }
        }

        return $this;
    }

  

  
  

}

src/Form/EmployedType.php
<?php

namespace App\Form;

use App\Entity\Employed;
use App\Entity\Unidadesoperativas;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\Range;


class EmployedType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Cedula',TextType::class,[
                'label'=>'Cédula',
                'constraints' => [new Regex([
                    'pattern'=>'/^[0-9,$]*$/',
                    'message' =>"El campo solo debe tener números"
                 ])
            ] ])
            ->add('email',EmailType::class,[
                'label'=>'Correo Electrónico', 
            ])
            ->add('Nombre',TextType::class,[
                'label'=>'Nombres Completos', 
            ])
            ->add('Apellido',TextType::class,[
                'label'=>'Apellidos Completos', 
            ])

            ->add('foto',FileType::class,[
                'label' => 'Fotografía del Médico (JPG) 500Kb',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '500k',
                        'mimeTypes' => [
                            'image/jpeg',
                        ],
                        'mimeTypesMessage' => 'Porfavor subir una imagen en formato jpg',
                    ])
                ],
           ])

            ->add('Fecha_Ingreso',BirthdayType::class,[
                'label'=>'Fecha de ingreso', 
                'years' => range(1950, date("Y")),
            'constraints' => new Range(['max'=>"now"]),
                    'placeholder' => [
                        'year' => 'Año', 'month' => 'Mes', 'day' => 'Dia'
                       
                    ]
            ])
            ->add('unidadesoperativas',EntityType::class,[
                'class'=>Unidadesoperativas::class,
                'label'=>'Unidad Operativa', 
                'placeholder'=>'Seleccione una Unidad Operativa',
                'choice_label'=>'nombre'
            ])
            ->add('Profesion',TextType::class,[
                'label'=>'Especialidad del Médico', 
            ])

            ->add('roles', ChoiceType::class, [
                'required' => true,
                'multiple' => true,
                'expanded' => true,
                'choices'  => [
                  'Médico' => 'ROLE_MEDICO',
                  'Super_Admin' => 'ROLE_SUPER_ADMIN',
                ],
            ])
           
            ->add('estado',ChoiceType::class,[
                'choices'=>[
                 'Activo' => 'Activo',
                 'Inactivo' => 'Inactivo',
              
                ]
             ])

         
            ->add('is_active',CheckboxType::class,[
                'label'=>'Desbloquear/Bloquear'
                
            ])
        ;

            
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Employed::class,
        ]);
    }
}

src/Controller/EmployedController.php
<?php

namespace App\Controller;

use App\Entity\Employed;

use App\Entity\Paralelo;
use App\Form\EmployedType;
use App\Form\ParaleloType;
use App\Repository\EmployedRepository;
use App\Repository\ParaleloRepository;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

/**
 * @Route("/employed")
 * @IsGranted("ROLE_SUPER_ADMIN",message="No tiene acceso a esta pagina")
 */
class EmployedController extends AbstractController
{
    /**
     * @Route("/", name="employed_index", methods={"GET"})
     */
    public function index(EmployedRepository $employedRepository): Response
    {
        return $this->render('employed/index.html.twig', [
            'employeds' => $employedRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="employed_new", methods={"GET","POST"})
   
     */
    public function new(Request $request,UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $employed = new Employed();
        $form = $this->createForm(EmployedType::class, $employed);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            $file= $request->files->get('employed')['foto'];
            if ($file) {
         
            $filname= md5(uniqid()) .'.'. $file->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('fotos_directory'),
                        $filname
                    );
                } catch (FileException $e) {
                    throw  new \Exception('Error al subir archivos');
                    // ... handle exception if something happens during file upload
                }
                  $employed->setFoto($filname);
                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
               
            }
            
            $employed->setUsername($form['Cedula']->getData());
            $employed->setPassword($passwordEncoder->encodePassword( $employed,$form['Cedula']->getData()));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($employed);
            $entityManager->flush();
            return $this->redirectToRoute('employed_index');
        }
        return $this->render('employed/new.html.twig', [
            'employed' => $employed,
            'form' => $form->createView(),
        ]);
    }

  

    
     


  


    /**
     * @Route("/{id}/edit", name="employed_edit", methods={"GET","POST"})
    
     */
    public function edit(Request $request, Employed $employed ,UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $form = $this->createForm(EmployedType::class, $employed);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file= $request->files->get('employed')['foto'];
            if ($file) {
         
            $filname= md5(uniqid()) .'.'. $file->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('fotos_directory'),
                        $filname
                    );
                } catch (FileException $e) {
                    throw  new \Exception('Error al subir archivos');
                    // ... handle exception if something happens during file upload
                }
                  $employed->setFoto($filname);
                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
               
            }
            $employed->setUsername($form['Cedula']->getData());
           
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('employed_index');
        }

        return $this->render('employed/edit.html.twig', [
            'employed' => $employed,
            'form' => $form->createView(),
        ]);
    }



    /**
     * @Route("delete/{id}", name="employed_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Employed $employed): Response
    {
        if ($this->isCsrfTokenValid('delete'.$employed->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($employed);
            $entityManager->flush();
        }

        return $this->redirectToRoute('employed_index');
    }
}

templates/employed/_delete_form.html.twig
<form method="post" action="{{ path('employed_delete', {'id': employed.id}) }}" onsubmit="Está seguro de eliminar?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employed.id) }}">
    <button class="btn btn-outline-danger btn-block btn-sm">
    <i class="fas fa-trash-alt"> Eliminar</i>
    </button>
</form>

templates/employed/_form.html.twig
<div class="container">
    <div class="row py-5 mt-4 align-items-center">
        <!-- For Demo Purpose -->
     
        <!-- Registeration Form -->
       
        {{ form_start(form) }}
            
            <div class="row">
                <!-- Cédula médico -->
                    <div class="col-md-6">
                          {{ form_row(form.Cedula,{
                              attr: {
                            'placeholder': 'Digite Número de Cédula'
                               }
                                 }) }}
                    </div>
                    <!-- Correo -->
                    <div class="col-md-6">
                          {{ form_row(form.email,{
                              attr: {
                            'placeholder': 'nombre@correo.com'
                               }
                                 }) }}
                    </div>
                    <!-- Nombres -->
                    <div class="col-md-6">
                          {{ form_row(form.Nombre,{
                              attr: {
                            'placeholder': 'Ingrese 2 Nombres'
                               }
                                 }
                     
                     ) }}
                    </div>

                    <!-- Apellidos -->
                    <div class="col-md-6">
                          {{ form_row(form.Apellido,{
                              attr: {
                            'placeholder': 'Ingrese 2 Apellidos'
                               }
                                 }) }}
                    </div>

                       <!-- Fotografía del médico -->
                      <div class="col-md-12">
                             {{ form_row(form.foto, {
                              attr: {
                            'placeholder': 'Foto de perfil'
                               }
                                 }) }}
                    </div>
                    
                     
                    <div class="col-md-6">
                       
                        {{ form_row(form.Profesion,{
                              attr: {
                            'placeholder': 'Medicina General'
                               }
                                 }) }}
                    </div>

                     <div class="col-md-6">
                       
                        {{ form_row(form.unidadesoperativas,{
                              attr: {
                            'placeholder': 'Unidades Operativas'
                               }
                                 }) }}
                    </div>

                  <!-- Roles -->
                    <div class="col-md-6">
                         {{ form_row(form.roles) }}
                    </div>

                  <!-- Fecha de Ingreso -->
                    <div class="col-md-6">
                            {{ form_row(form.Fecha_Ingreso) }}
                    </div>

                  <!-- Estado trabaja o no en la empresa -->
                    <div class="input-group col-lg-12 mb-4">
                         {{ form_row(form.estado) }}
                    </div>

                  <!-- bloquear/desbloquear usuario -->
                    <div class="input-group col-lg-12 mb-4">
                         {{ form_row(form.is_active) }}
                    </div>

              <button class="btn btn-block bg-gradient-primary btn-sm">
                <i class="fas fa-save"> </i>
                  {{ button_label|default('Registrar') }}
              </button>
            </div> 
            {{ form_end(form) }}
    </div>
</div>

templates/employed/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Actualizar Datos del Médico{% endblock %}

{% block body %}
<div class="card-body p-5 bg-white rounded">
    <h1>Actualizar Datos del Médico</h1>

    {{include('employed/_form.html.twig', {'button_label': 'Actualizar Datos'})}}
    {{ include('employed/_delete_form.html.twig') }}
    <button class="btn btn-block btn-outline-warning btn-sm">
      <a href="{{ path('employed_index') }}"><i class="fas fa-chevron-left"> Regresar a lista de Médicos</i>
      </a>
    </button>
    
    
    <div>
{% endblock %}
{% block javascripts %}

    <script> 
        $(function() {
  // Sidebar toggle behavior
  $('#sidebarCollapse').on('click', function() {
    $('#sidebar, #content').toggleClass('active');
  });
});
        </script>

<script>     
                $('.custom-file-input').on('change', function(event) {
                    var inputFile = event.currentTarget;
                    $(inputFile).parent()
                        .find('.custom-file-label')
                        .html(inputFile.files[0].name);
                });
            </script>
 {% endblock %}

templates/employed/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="page-header">
   <img src="{{ asset('image/Recursos_Banner 1.jpg') }}" height="100" width=100% >
</div> 
<div class="card-body p-5 bg-white rounded">

<button class="btn bg-primary btn-sm">
    <a href="{{ path('employed_new') }}">
    Registrar Nuevo Médico
    <i class="fas fa-plus-square"></i>
    </a>
    </button>
    </br>
       <div class="table-responsive">
            <table id="example" style="width:100%" class="content-table table-sm">
              <thead>
                <tr>
                <th>Cédula</th>
                <th>Nombre</th>
                <th>Foto</th>
                <th>Especialidad</th>
                <th>Unidad Operativa</th>
                <th>Fecha Ingreso</th>
                <th>Roles</th>
                <th>Bloqueado</th>
                <th>Acciones</th>
                </tr>
              </thead>
              <tbody>
                 {% for employed in employeds %}
            <tr>
                <td>{{ employed.username }}</td>
                <td>{{ employed.Nombre }} {{ employed.Apellido }}</td>
                <td> <img src="{{ asset('uploads/'~employed.foto) }}" alt="" width="50" class="mr-3 rounded-circle img-thumbnail shadow-sm"></td>
                <td>{{ employed.Profesion }}</td>
                <td>{{ employed.unidadesoperativas.nombre }}</td>
                <td>{{ employed.FechaIngreso ? employed.FechaIngreso|date('Y-m-d') : '' }}</td>
                <td>{{ employed.roles ? employed.roles|json_encode : '' }}</td>
                <td>{{ employed.isActive ? 'No' : 'Si' }}</td>
                <td>
                    <a href="{{ path('employed_edit', {'id': employed.id}) }}" title="Editar"><i class="fas fa-edit"></i> </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">No Existen Registros</td>
            </tr>
        {% endfor %}
              </tbody>
            </table>
            </div>
</div>

 
{% endblock %}

{% block javascripts %}

  <script> 
          $(document).ready(function() {
    $('#example').DataTable({
        dom: 'Plfrtip',
       
          columnDefs: [
        
             {
                searchPanes: {
                    show: true
                },
                targets: [6]
            },

        
           
        ],
       language: {
            url: 'https://cdn.datatables.net/plug-ins/1.10.22/i18n/Spanish.json',

             searchPanes: {
                clearMessage: 'Limpiar Panel',
                title: {
                     _: 'Filters Selected - %d',
                    0: 'Ningun Filtro Seleccionado',
                    1: 'Filtros seleccionado - %d', 
                   
                },
                

            }
        },

       
         'responsive': true,
    });
});
   
  
        </script>


  

   {% endblock %}

templates/employed/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nuevo Médico{% endblock %}

{% block body %}
<div class="card-body p-5 bg-white rounded">
    <h1>Registrar Nuevo Médico</h1>

    {{ include('employed/_form.html.twig') }}

    <a href="{{ path('employed_index') }}">
        <button class="btn btn-block btn-outline-warning btn-sm">
            <i class="fas fa-chevron-left">Regresar a lista de médicos</i>
        </button>
    </a>
    </div>

{% endblock %}

{% block javascripts %}


<script>     
              $('.custom-file-input').on('change', function(event) {
                    var inputFile = event.currentTarget;
                    $(inputFile).parent()
                        .find('.custom-file-label')
                        .html(inputFile.files[0].name);
                });
            </script>
 {% endblock %}

templates/employed/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Médico{% endblock %}

{% block body %}
<div class="card-body p-5 bg-white rounded">
  

    <div class="row py-5 mt-4 align-items-center">
        <!-- For Demo Purpose -->
        <div class="col-md-5 pr-lg-5 mb-5 mb-md-0">
                    <div class="table-responsive">
            
            <table class="table">
        <tbody>
             <h4>Empleado</h4>
            <tr>
                <th>Cedula</th>
                <td>{{ emp.Cedula }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ emp.Nombre }} {{ emp.Apellido }}</td>
            </tr>
            
            <tr>
                <th>Foto</th>
                <td><img src="{{ asset('uploads/'~emp.Foto) }}" alt="..." width="50" class="mr-3 rounded-circle img-thumbnail shadow-sm"></td>
            </tr>
           
        </tbody>
    </table> 
   </div>
        </div>

        <!-- Registeration Form -->
        <div class="col-md-7 col-lg-6 ml-auto">
        {{ form_start(form) }}
      {{ form_widget(form.estado) }} </br>
                <div class="row">
                 
                    <div class="input-group col-lg-6 mb-4">
                      {{ form_widget(form.Carrera) }}
                    </div>

                    <!-- Last Name -->
                    <div class="input-group col-lg-6 mb-4">
                       {{ form_widget(form.Materia) }} 
                        
                    </div>

                     <div class="input-group col-lg-12 mb-4">
                         {{ form_widget(form.grupo) }}
                        
                    </div>
    
        </br>
    <button class="btn btn-primary">{{ button_label|default('Guardar') }}</button>

</div>
{{ form_end(form) }}

        </div>
       
    </div>


      <div class="table-responsive">
        <table class="table">
        <thead>
            <tr>
                <th>Carrera</th>
                <th>Materia</th>
                <th>Nivel</th>
                <th>Paralelo</th>
               
               
            </tr>
        </thead>
        <tbody>
        {% for n in paralelo %}
            <tr>
                <td>{{ n.Carrera }}</td>
               <td>{{ n.Materia }}</td>
               <td>{{ n.Nivel}}</td>
                <td>{{n.Paralelo}} </td>
               
                
            </tr>
        {% else %}
            <tr>
                <td colspan="18">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
      </div>
      


   <a href="{{ path('employed_index') }}">Regresar a la lista</a>
   
</div>
   
{% endblock %}

{% block javascripts %}

<script> 
        $(function() {
  // Sidebar toggle behavior
  $('#sidebarCollapse').on('click', function() {
    $('#sidebar, #content').toggleClass('active');
  });
});
</script>
<script>
        var $notas_Carrera = $('#paralelo_Carrera')
        var $token = $('#paralelo_token')
$notas_Carrera.change(function ()
{
    var $form =$(this).closest('form')
    var data={}
    data[$token.attr('name')]= $token.val()
    data[$notas_Carrera.attr('name')]= $notas_Carrera.val()

    $.post($form.attr('action'),data).then(function (response)
    {
        $('#paralelo_Materia').replaceWith(
            $(response).find('#paralelo_Materia')
        )
    })

})
function log($msg){
    console.log($msg)
}
</script>
{% endblock %}