src/Entity/Employed.php
<?php

namespace App\Entity;

use App\Repository\EmployedRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EmployedRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"Cedula","email"},
 *     message="Este usuario ya existe"
 * )
 */
class Employed implements AdvancedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


     /**
     * @ORM\Column(type="string", length=10,unique=true)
     * @Assert\NotBlank()
     * @Assert\Length(
     *      min = 10,
     *      max = 10,
     * )
     */
    private $Cedula;


    /**
     * @ORM\Column(type="string", length=255,unique=true)
     * @Assert\Email(
     *     message = "El email '{{ value }}' no es valido."
     * )
     */
    private $email;

   

    /**
     * @ORM\Column(type="string", length=255, )
     */
    private $Nombre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Apellido;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $foto;




    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Assert\Range(
     *      max = "now"
     * )
     */
    private $Fecha_Ingreso;



    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Profesion;


    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $username;




    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    
    public function __construct()
    {
      
      
        $this->is_active = true;
        $this->Fecha_Ingreso= new \DateTime();
        $this->paralelo = new ArrayCollection();
        $this->consulta = new ArrayCollection();
        $this->reset_pasword = new ArrayCollection();
      
      
      
    }

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

     /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;


     /**
     * @ORM\Column(type="string", length=64)
     */
    private $estado;

    /**
     * @ORM\ManyToOne(targetEntity=Unidadesoperativas::class, inversedBy="employed")
     * @ORM\JoinColumn(nullable=false)
     */
    private $unidadesoperativas;

    /**
     * @ORM\OneToMany(targetEntity=Consulta::class, mappedBy="employed", orphanRemoval=true)
     */
    private $consulta;

   



 


    public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return true;
    }

    public function isCredentialsNonExpired()
    {
        return true;
    }

    public function isEnabled()
    {
        return $this->is_active;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
       

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getCedula(): ?string
    {
        return $this->Cedula;
    }

    public function setCedula(string $Cedula): self
    {
        $this->Cedula = $Cedula;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getApellido(): ?string
    {
        return $this->Apellido;
    }

    public function setApellido(string $Apellido): self
    {
        $this->Apellido = $Apellido;

        return $this;
    }

    public function getFoto(): ?string
    {
        return $this->foto;
    }

    public function setFoto(?string $foto): self
    {
        $this->foto = $foto;

        return $this;
    }


    public function getFechaIngreso(): ?\DateTimeInterface
    {
        return $this->Fecha_Ingreso;
    }

    public function setFechaIngreso(?\DateTimeInterface $Fecha_Ingreso): self
    {
        $this->Fecha_Ingreso = $Fecha_Ingreso;

        return $this;
    }

  
    public function getProfesion(): ?string
    {
        return $this->Profesion;
    }

    public function setProfesion(string $Profesion): self
    {
        $this->Profesion = $Profesion;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

    public function getUnidadesoperativas(): ?Unidadesoperativas
    {
        return $this->unidadesoperativas;
    }

    public function setUnidadesoperativas(?Unidadesoperativas $unidadesoperativas): self
    {
        $this->unidadesoperativas = $unidadesoperativas;

        return $this;
    }

    /**
     * @return Collection|Consulta[]
     */
    public function getConsulta(): Collection
    {
        return $this->consulta;
    }

    public function addConsultum(Consulta $consultum): self
    {
        if (!$this->consulta->contains($consultum)) {
            $this->consulta[] = $consultum;
            $consultum->setEmployed($this);
        }

        return $this;
    }

    public function removeConsultum(Consulta $consultum): self
    {
        if ($this->consulta->removeElement($consultum)) {
            // set the owning side to null (unless already changed)
            if ($consultum->getEmployed() === $this) {
                $consultum->setEmployed(null);
            }
        }

        return $this;
    }

  

  
  

}

src/Entity/Pacientes.php
<?php

namespace App\Entity;

use App\Repository\PacientesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PacientesRepository::class)
 * @UniqueEntity(fields={"cedula"}, message="Esta cedula ya existe")
 */
class Pacientes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $tipo_identificacion;


    /**
     * @ORM\Column(type="string",length=17,unique=true)
     * @Assert\NotBlank()
     * @Assert\Length(
     *      min = 10,
     *      max = 17,
     * )
     */
    private $cedula;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $pnombre;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $snombre;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $papellido;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $sapellido;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $sexo;
    
    /**
     * @ORM\Column(type="date", nullable=true)
     * @Assert\Range(
     *      max = "now"
     * )
     */
    private $fecha_nacimiento;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $estado_civil;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $tipo_sangre;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $discapacidad = [];

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $tipo_discapacidad;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $religion;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $identidad_genero;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     * @Assert\Email(
     *     message = "El email '{{ value }}' no es valido."
     * )
     */
    private $email_paciente;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     * @Assert\Length(
     *      min = 10,
     *      max = 30,
     * )
     */
    private $celular;

  

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Assert\Range(
     *      max = "now"
     * )
     */
    private $fecha_ingreso;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $historia_clinica;

    /**
     * @ORM\ManyToOne(targetEntity=Ciudad::class, inversedBy="pacientes")
     * @ORM\JoinColumn(nullable=true)
     */
    private $ciudad;

    /**
     * @ORM\OneToMany(targetEntity=Consulta::class, mappedBy="pacientes", orphanRemoval=true)
     */
    private $consulta;

    /**
     * @ORM\OneToMany(targetEntity=AntNoPatologicos::class, mappedBy="pacientes", orphanRemoval=true)
     */
    private $antNoPatologicos;

    /**
     * @ORM\OneToMany(targetEntity=AntPatologicos::class, mappedBy="pacientes", orphanRemoval=true)
     */
    private $antPatologicos;

    /**
     * @ORM\OneToMany(targetEntity=AntReproductivos::class, mappedBy="pacientes", orphanRemoval=true)
     */
    private $antReproductivos;

    /**
     * @ORM\OneToMany(targetEntity=Diagnostico::class, mappedBy="pacientes", orphanRemoval=true)
     */
    private $diagnosticos;

    /**
     * @ORM\OneToMany(targetEntity=OtrosAntecedentes::class, mappedBy="pacientes", orphanRemoval=true)
     */
    private $otrosAntecedentes;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $posicion;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $identificacion_etnica;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $nivel_instruccion;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $calle_principal;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $numero_casa;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sector;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $calle_secundaria;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $etnia;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $is_active;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $orientacion_sexual;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $lateralidad;

    /**
     * @ORM\OneToMany(targetEntity=AntHeredofamiliares::class, mappedBy="pacientes", orphanRemoval=true)
     */
    private $antHeredofamiliares;

    /**
     * @ORM\ManyToOne(targetEntity=PuestoTrabajo::class, inversedBy="pacientes")
     * @ORM\JoinColumn(nullable=true)
     */
    private $puesto_trabajo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $aptitudes;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $observacion;

    /**
     * @ORM\OneToMany(targetEntity=AntQuirugicos::class, mappedBy="pacientes", orphanRemoval=true)
     */
    private $antQuirugicos;

    /**
     * @ORM\OneToMany(targetEntity=AntLaborales::class, mappedBy="pacientes", orphanRemoval=true)
     */
    private $antLaborales;

    /**
     * @ORM\ManyToOne(targetEntity=Unidadesoperativas::class, inversedBy="pacientes")
     * @ORM\JoinColumn(nullable=true)
     */
    private $unidades_operativas;

 
  

    public function __construct()
    {
      
      
        $this->consulta = new ArrayCollection();
        $this->signos_vitales = new ArrayCollection();
        $this->examen_fisico = new ArrayCollection();
        $this->antNoPatologicos = new ArrayCollection();
        $this->antPatologicos = new ArrayCollection();
        $this->antReproductivos = new ArrayCollection();
        $this->diagnosticos = new ArrayCollection();
        $this->otrosAntecedentes = new ArrayCollection();
        $this->antHeredofamiliares = new ArrayCollection();
        $this->antQuirugicos = new ArrayCollection();
        $this->antLaborales = new ArrayCollection();
     
    }


    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTipoIdentificacion(): ?string
    {
        return $this->tipo_identificacion;
    }

    public function setTipoIdentificacion(?string $tipo_identificacion): self
    {
        $this->tipo_identificacion = $tipo_identificacion;

        return $this;
    }

    public function getCedula(): ?string
    {
        return $this->cedula;
    }

    public function setCedula(?string $cedula): self
    {
        $this->cedula = $cedula;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPnombre(): ?string
    {
        return $this->pnombre;
    }

    public function setPnombre(?string $pnombre): self
    {
        $this->pnombre = strtoupper($pnombre);

        return $this;
    }

    public function getSnombre(): ?string
    {
        return $this->snombre;
    }

    public function setSnombre(?string $snombre): self
    {
        $this->snombre = strtoupper($snombre);

        return $this;
    }

    public function getPapellido(): ?string
    {
        return $this->papellido;
    }

    public function setPapellido(?string $papellido): self
    {
        $this->papellido = strtoupper($papellido);

        return $this;
    }

    public function getSapellido(): ?string
    {
        return $this->sapellido;
    }

    public function setSapellido(?string $sapellido): self
    {
        $this->sapellido = strtoupper($sapellido);

        return $this;
    }

    public function getSexo(): ?string
    {
        return $this->sexo;
    }

    public function setSexo(?string $sexo): self
    {
        $this->sexo = $sexo;

        return $this;
    }

    public function getFechaNacimiento(): ?\DateTimeInterface
    {
        return $this->fecha_nacimiento;
    }

    public function setFechaNacimiento(?\DateTimeInterface $fecha_nacimiento): self
    {
        $this->fecha_nacimiento = $fecha_nacimiento;

        return $this;
    }

    public function getEstadoCivil(): ?string
    {
        return $this->estado_civil;
    }

    public function setEstadoCivil(?string $estado_civil): self
    {
        $this->estado_civil = $estado_civil;

        return $this;
    }

    public function getTipoSangre(): ?string
    {
        return $this->tipo_sangre;
    }

    public function setTipoSangre(?string $tipo_sangre): self
    {
        $this->tipo_sangre = $tipo_sangre;

        return $this;
    }

    public function getDiscapacidad(): array
    {
        $discapacidad = $this->discapacidad;
        return array($discapacidad);
    }

    public function setDiscapacidad(array $discapacidad): self
    {
        $this->discapacidad = $discapacidad;

        return $this;
    }

    public function getTipoDiscapacidad(): ?string
    {
        return $this->tipo_discapacidad;
    }

    public function setTipoDiscapacidad(?string $tipo_discapacidad): self
    {
        $this->tipo_discapacidad = strtoupper($tipo_discapacidad);

        return $this;
    }

    public function getReligion(): ?string
    {

templates/pacientes/_delete_form.html.twig
<form method="post" action="{{ path('pacientes_delete', {'id': paciente.id}) }}" onsubmit="return confirm('Está seguro que desea eliminar al paciente?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ paciente.id) }}">
    <button class="btn btn-block btn-outline-danger btn-sm"> <i class="fas fa-trash-alt"> </i> Eliminar </button>
</form>

templates/pacientes/exel_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pacientes{% endblock %}

{% block body %}
    <div class="card-body p-5 bg-white rounded">

    <a href="{{ path('pacientes_new') }}">
    <button class="btn btn-block bg-primary btn-sm">
    <i class="fas fa-plus-square"></i>
    Crear Nuevo Paciente
    </button>
    </a>

      
{{ form_start(form) }}
 </br>
      {{ form_row(form.file, {
        attr: {
            'placeholder': 'Seleccione un archivo'
        }
    }) }}
       <button class="btn btn-block btn-success btn-sm">
    <i class="fas fa-file-import"></i>
                  {{ button_label|default('Importar datos') }}
    </button>
     {{ form_end(form) }}
     </br>
     
       <div class="table-responsive">
       <table id="example" class="content-table table-sm" style="width:100%">
        <thead>
            <tr>
                <th>Cedula</th>
                <th>Imagen</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Fecha Nacimiento</th>
                <th>Edad</th>
                <th>Fecha Ingreso</th>
                <th>Provincia</th>
                <th>Ciudad</th>
         
            </tr>
        </thead>
        <tbody>
        {% for paciente in pacientes %}
            <tr>
                <td>{{ paciente.cedula }}</td>
                <td><img src="{{ asset('uploads/'~paciente.image) }}" alt="" width="50" class="mr-3 rounded-circle img-thumbnail shadow-sm"></td>
                <td>{{ paciente.pnombre }} {{ paciente.snombre }}</td>
                <td>{{ paciente.papellido }} {{ paciente.sapellido }}</td>
                <td>{{ paciente.fechaNacimiento ? paciente.fechaNacimiento|date('Y-m-d') : '' }}</td>
                <td>{{ date('now').diff((date(paciente.fechaNacimiento))).format('%y años') }}</td>
                <td>{{ paciente.fechaIngreso ? paciente.fechaIngreso|date('Y-m-d') : '' }}</td>
                <td>{{ paciente.ciudad.provincia.nombre}}</td>
                <td>{{ paciente.ciudad.nombre}}</td>
              

            </tr>
        {% else %}
            <tr>
                <td colspan="25">No Existen Registros</td>
            </tr>
        {% endfor %}
          
        </tbody>
        <tfoot>
        </tfoot>
       
    </table>

       
            </div>
      

        </div>

 
{% endblock %}


{% block javascripts %}
<script> 
          
        $(function() {
  // Sidebar toggle behavior
  $('#sidebarCollapse').on('click', function() {
    $('#sidebar, #content').toggleClass('active');
  });
});
        </script>

  <script> 
       $(document).ready(function() {
        $('#example').DataTable( {
            language: {
            url: 'https://cdn.datatables.net/plug-ins/1.10.22/i18n/Spanish.json'
        },

       
         'responsive': true,
         
  } );
    } );

  
 </script>


  <script> 
       $(document).ready(function() {
        $('#example1').DataTable( {
            language: {
            url: 'https://cdn.datatables.net/plug-ins/1.10.22/i18n/Spanish.json'
        },

       
         'responsive': true,
         
  } );
    } );

  
 </script>


  

   {% endblock %}

templates/pacientes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pacientes{% endblock %}

{% block body %}
<div class="page-header">
   <img src="{{ asset('image/Recursos_Banner 2.jpg') }}" height="100" width=100% >
</div> 
    <div class="card-body p-5 bg-white rounded">
    <a href="{{ path('pacientes_new') }}">
    <button class="btn btn-block bg-primary btn-sm">
    <i class="fas fa-plus-square"></i>
    Crear Nuevo Paciente
    </button>
    </a>

  {% if is_granted("ROLE_SUPER_ADMIN") %}
      
{{ form_start(form) }}
 </br>
      {{ form_row(form.file, {
        attr: {
            'placeholder': 'Seleccione un archivo'
        }
    }) }}
       <button class="btn btn-block btn-success btn-sm">
    <i class="fas fa-file-import"></i>
                  {{ button_label|default('Importar datos') }}
    </button>
     {{ form_end(form) }}
 {% endif %}
     </br>

  {% if is_granted('ROLE_MEDICO') or is_granted('ROLE_SUPER_ADMIN') %}
       <div class="table-responsive">
       <table id="example" class="content-table table-sm" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Cedula</th>
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Fecha Nacimiento</th>
                <th>Edad</th>
                <th>Fecha Ingreso</th>
                <th>Provincia</th>
                <th>Ciudad</th>
                 <th>Regional</th>
                 <th>Oficina</th>
                <th>Puesto de Trabajo </th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for paciente in pacientes %}
            <tr>
           
                <td>{{ paciente.id }}</td>
                <td>{{ paciente.cedula }}</td>
               
                <td>{{ paciente.pnombre }} {{ paciente.snombre }}</td>
                <td>{{ paciente.papellido }} {{ paciente.sapellido }}</td>
                <td>{{ paciente.fechaNacimiento ? paciente.fechaNacimiento|date('Y-m-d') : '' }}</td>
                <td>{{ date('now').diff((date(paciente.fechaNacimiento))).format('%y años') }}</td>
                <td>{{ paciente.fechaIngreso ? paciente.fechaIngreso|date('Y-m-d') : '' }}</td>
                 <td>
                {% if  paciente.ciudad.provincia.nombre is defined and paciente.ciudad.provincia.nombre is null  %}
                .....
                {% elseif paciente.ciudad.provincia.nombre  is defined and paciente.ciudad.provincia.nombre  is not null  %}
                {{ paciente.ciudad.provincia.nombre}}
                {% endif %}
                 </td>
                 <td>
                {% if  paciente.ciudad.nombre is defined and paciente.ciudad.nombre is null  %}
                .....
                {% elseif paciente.ciudad.nombre  is defined and paciente.ciudad.nombre  is not null  %}
                {{ paciente.ciudad.nombre}}
                {% endif %}
                 </td>
                <td> {{ paciente.unidadesoperativas.regional}}  </td>
                <td>{{ paciente.unidadesoperativas.nombre}} </td>
                
                <td>

                {% if  paciente.puestotrabajo.nombre is defined and paciente.puestotrabajo.nombre is null  %}
                   ....
                  {% elseif paciente.puestotrabajo.nombre is defined and paciente.puestotrabajo.nombre is not null  %}
                     {{ paciente.puestotrabajo.nombre}}
                {% endif %}
                
                </td>

                <td>

                    <a href="{{ path('consulta_new', {'id': paciente.id}) }}" title="Ficha Médica"><i class="fas fa-calendar-plus"></i></a> 
                   
                </td>

            </tr>
        {% else %}
            <tr>
                <td colspan="25">No Existen Registros</td>
            </tr>
        {% endfor %}
          
        </tbody>
        <tfoot>
        </tfoot>
       
    </table>
 </div>
  {% endif %}


      

        </div>

 
{% endblock %}


{% block javascripts %}
<script> 
          
        $(function() {
  // Sidebar toggle behavior
  $('#sidebarCollapse').on('click', function() {
    $('#sidebar, #content').toggleClass('active');
  });
});
        </script>

  <script> 
       $(document).ready(function() {
        $('#example').DataTable( {

             
        
            language: {
            url: 'https://cdn.datatables.net/plug-ins/1.10.22/i18n/Spanish.json'
        },

          dom: 'Bfrtip',
       
         'responsive': true,
         "order": [[ 0, "desc" ]],
 

         
  } );
    } );

  
 </script>





  

   {% endblock %}

templates/pacientes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pacientes{% endblock %}

{% block body %}
    <div class="card-body p-5 bg-white rounded">
    <h5>Paciente</h5>
    
    <a href="{{ path('pacientes_index') }}" class="btn"><i class="fas fa-chevron-left"></i> </a>
    <a href="{{ path('pacientes_edit', {'id': paciente.id}) }}" class="btn"><i class="fas fa-edit"></i></a> 
    {{ include('pacientes/_delete_form.html.twig') }}
    
    
    <table class="table table-striped">
    
    <div class="contenedor">
    
        <tbody>
          
            <tr>
                <th>Cedula</th>
                <td>{{ paciente.cedula }}</td>
            </tr>
             <tr>
                <th>Historia Clinica</th>
                <td>{{ paciente.historiaclinica}}</td>
            </tr>

             <div class="col-md-5 pr-lg-5 mb-5 mb-md-0">
            
            <img src="{{ asset('uploads/'~paciente.image) }}" alt=""  class="img-fluid mb-3 d-none d-md-block  img-thumbnail shadow-sm" >
        </div>
            <tr>
                <th>Primer Nombre</th>
                <td>{{ paciente.pnombre }}</td>
            </tr>
            <tr>
                <th>Segundo Nombre</th>
                <td>{{ paciente.snombre }}</td>
            </tr>
            <tr>
                <th>Primer Apellido</th>
                <td>{{ paciente.papellido }}</td>
            </tr>
            <tr>
                <th>Segundo Apellido</th>
                <td>{{ paciente.sapellido }}</td>
            </tr>
            <tr>
                <th>Sexo</th>
                <td>{{ paciente.sexo }}</td>
            </tr>
            <tr>
                <th>Fecha_nacimiento</th>
                <td>{{ paciente.fechaNacimiento ? paciente.fechaNacimiento|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Estado_civil</th>
                <td>{{ paciente.estadoCivil }}</td>
            </tr>
            <tr>
                <th>Tipo_sangre</th>
                <td>{{ paciente.tipoSangre }}</td>
            </tr>
            <tr>
                <th>Discapacidad</th>
                <td>{{  paciente.discapacidad }}</td>
                
            </tr>
            <tr>
                <th>Tipo_discapacidad</th>
                <td>{{ paciente.tipoDiscapacidad }}</td>
            </tr>
            <tr>
                <th>Religion</th>
                <td>{{ paciente.religion }}</td>
            </tr>
            <tr>
                <th>Identidad_genero</th>
                <td>{{ paciente.identidadGenero }}</td>
            </tr>
            <tr>
                <th>Email_paciente</th>
                <td>{{ paciente.emailPaciente }}</td>
            </tr>
            <tr>
                <th>Celular</th>
                <td>{{ paciente.celular }}</td>
            </tr>
            <tr>
                <th>Fecha_ingreso</th>
                <td>{{ paciente.fechaIngreso ? paciente.fechaIngreso|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
        </div>
    </table>

   
   
   
    </div>
{% endblock %}